### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by tweissin** [maghoff/cargo-license-hound#3]
Hi, cool repo. I found this repo from this post: https://www.reddit.com/r/rust/comments/7jrm98/licensing_question/

Anyway I tried running `cargo install --git https://github.com/maghoff/cargo-license-hound` and I got this error

```
   Compiling serde_ignored v0.0.3
error: failed to run custom build command for `openssl v0.9.24`

Caused by:
  process didn't exit successfully: `/var/folders/2j/g5qt9wws2dq3h38yy9xt47c00000gr/T/cargo-installvqNtsp/release/build/openssl-c0b52e41efd13c6c/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /Users/tweissin/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-license-hound v0.1.0 (https://github.com/maghoff/cargo-license-hound#6502ccf3)`, intermediate artifacts can be found at `/var/folders/2j/g5qt9wws2dq3h38yy9xt47c00000gr/T/cargo-installvqNtsp`

Caused by:
  build failed
```

I then found this: https://github.com/paritytech/substrate/issues/800

which pointed me here: https://docs.rs/openssl/0.10.29/openssl/

I'm on MacOS so I ran `brew install openssl@1.1` but it told me that it was already installed.

```
Warning: openssl@1.1 1.1.1g is already installed and up-to-date
To reinstall 1.1.1g, run `brew reinstall openssl@1.1`
```

Any ideas? It's not really your issue but just seeing if you have any ideas.

Thanks
Tom

**Comment by maghoff** [comment]
Hi, thanks for getting in touch!
Sorry, I don't have any meaningful ideas. It has been a long time since I touched this repo, so most of the dependencies are really old. It could maybe be easier to get it working with more up-to-date dependencies. That's something you could try, and I would appreciate a PR if it turns out to help. Alternatively, you could look into getting older versions of openssl from brew. Good luck!
